uploads = []

[[generated]]
id = "EgFP_0k2VeANHxmpnzGG6"
uri = "file://artifacts/service-qc/assets/images/icon.png"
type = "image"
title = "serviceqc app icon"

[[outputs]]
id = "MnpwCauLVqlWr2VNGXy9y"
uri = "file://exports/testeurs-aidora-qc.csv"
type = "table"
title = "Testeurs AIDORA QC — Liste d'inscription"
