import { createContext, useContext, useState, type ReactNode } from "react";
import { Bot, Settings, Rocket, Laptop, TrendingUp, Search, Palette, Target } from "lucide-react";

export type Lang = "fr" | "en";

const BASE = import.meta.env.BASE_URL;

export const SLIDES_FR = [
  {
    badge: "IA & Automatisation",
    title: "L'IA au service de votre entreprise",
    punch: "Travaillez plus intelligemment.",
    desc: "Nous aidons les entreprises à automatiser leurs tâches et à exploiter l'IA pour gagner en productivité.",
    features: ["Outils de gestion sur mesure", "Automatisation avec l'IA", "Optimisation des outils existants", "Tableaux de bord intelligents"],
    image: `${BASE}slides/slide-ai.png`,
    gradient: "from-blue-950/95 via-blue-900/75 to-blue-800/20",
    icon: <Bot className="w-7 h-7" />,
  },
  {
    badge: "Solutions sur mesure",
    title: "Vos idées. Nos solutions technologiques.",
    punch: "Des outils performants pour avancer vite.",
    desc: "Solutions personnalisées pour gérer vos projets, clients, finances et analyses en un seul endroit.",
    features: ["Gestion de projets & tâches", "CRM & gestion clients", "Facturation & paiements", "Solutions 100 % personnalisées"],
    image: `${BASE}slides/slide-custom.png`,
    gradient: "from-indigo-950/95 via-indigo-900/75 to-indigo-800/20",
    icon: <Settings className="w-7 h-7" />,
  },
  {
    badge: "Optimisation IA",
    title: "Optimiser. Automatiser. Propulser.",
    punch: "Votre partenaire technologique de confiance.",
    desc: "Nous optimisons vos outils existants avec l'IA pour des résultats concrets et mesurables.",
    features: ["Automatisation intelligente", "Gain de temps et d'efficacité", "Meilleures décisions", "Croissance durable"],
    image: `${BASE}slides/slide-optimize.png`,
    gradient: "from-slate-950/95 via-slate-900/75 to-slate-800/20",
    icon: <Rocket className="w-7 h-7" />,
  },
  {
    badge: "Développement web",
    title: "Sites web modernes pour entreprises ambitieuses.",
    punch: "Design, performance et UX au cœur de tout.",
    desc: "Nous concevons des sites web sur mesure qui reflètent votre marque et convertissent vos visiteurs.",
    features: ["Sites web sur mesure", "Design réactif & moderne", "SEO & performance", "Maintenance & support"],
    image: `${BASE}slides/slide-web.png`,
    gradient: "from-cyan-950/95 via-cyan-900/75 to-cyan-800/20",
    icon: <Laptop className="w-7 h-7" />,
  },
  {
    badge: "Marketing digital",
    title: "Digital. Stratégie. Croissance.",
    punch: "Ensemble, propulsons votre entreprise.",
    desc: "Nous vous aidons à bâtir votre présence en ligne et atteindre vos objectifs avec une stratégie complète.",
    features: ["Stratégie digitale", "Gestion des réseaux sociaux", "Publicité en ligne (SEA & Social Ads)", "Contenu & image de marque"],
    image: `${BASE}slides/slide-marketing.png`,
    gradient: "from-blue-950/95 via-blue-900/75 to-blue-800/20",
    icon: <TrendingUp className="w-7 h-7" />,
  },
];

export const SLIDES_EN = [
  {
    badge: "AI & Automation",
    title: "AI at the service of your business",
    punch: "Work smarter. Grow faster.",
    desc: "We help businesses automate tasks and leverage AI to boost productivity.",
    features: ["Custom management tools", "AI automation", "Optimization of existing tools", "Smart dashboards"],
    image: `${BASE}slides/slide-ai.png`,
    gradient: "from-blue-950/95 via-blue-900/75 to-blue-800/20",
    icon: <Bot className="w-7 h-7" />,
  },
  {
    badge: "Custom solutions",
    title: "Your ideas. Our technology.",
    punch: "High-performance tools to move fast.",
    desc: "Customized solutions to manage your projects, clients, finances, and analytics in one place.",
    features: ["Project & task management", "CRM & client management", "Invoicing & payments", "100% custom solutions"],
    image: `${BASE}slides/slide-custom.png`,
    gradient: "from-indigo-950/95 via-indigo-900/75 to-indigo-800/20",
    icon: <Settings className="w-7 h-7" />,
  },
  {
    badge: "AI Optimization",
    title: "Optimize. Automate. Propel.",
    punch: "Your trusted technology partner.",
    desc: "We optimize your existing tools with AI for concrete, measurable results.",
    features: ["Intelligent automation", "Time savings & efficiency", "Better decisions", "Sustainable growth"],
    image: `${BASE}slides/slide-optimize.png`,
    gradient: "from-slate-950/95 via-slate-900/75 to-slate-800/20",
    icon: <Rocket className="w-7 h-7" />,
  },
  {
    badge: "Web development",
    title: "Modern websites for ambitious businesses.",
    punch: "Design, performance and UX at the core.",
    desc: "We design custom websites that reflect your brand and convert visitors into customers.",
    features: ["Custom websites", "Responsive & modern design", "SEO & performance", "Maintenance & support"],
    image: `${BASE}slides/slide-web.png`,
    gradient: "from-cyan-950/95 via-cyan-900/75 to-cyan-800/20",
    icon: <Laptop className="w-7 h-7" />,
  },
  {
    badge: "Digital marketing",
    title: "Digital. Strategy. Growth.",
    punch: "Together, let's propel your business.",
    desc: "We help you build your online presence and achieve your goals with a complete digital strategy.",
    features: ["Digital strategy", "Social media management", "Online advertising (SEA & Social Ads)", "Content & brand identity"],
    image: `${BASE}slides/slide-marketing.png`,
    gradient: "from-blue-950/95 via-blue-900/75 to-blue-800/20",
    icon: <TrendingUp className="w-7 h-7" />,
  },
];

export const BLOG_ARTICLES_FR = [
  {
    slug: "ia-secteur-public",
    category: "IA & Public",
    date: "12 mai 2026",
    readTime: "6 min",
    title: "L'IA au service du secteur public : opportunités et défis",
    excerpt: "Comment les administrations publiques canadiennes peuvent tirer parti de l'intelligence artificielle pour améliorer leurs services aux citoyens, tout en respectant les exigences de transparence et de protection des données.",
    sections: [
      { p: "L'intelligence artificielle n'est plus l'apanage des grandes entreprises technologiques. Aujourd'hui, les administrations publiques — municipalités, ministères, organismes parapublics — se trouvent à un carrefour décisif : intégrer l'IA pour mieux servir leurs citoyens, ou risquer de se laisser distancer par des attentes toujours croissantes." },
      { h: "Un contexte favorable au Québec", p: "Le Québec dispose d'un écosystème IA particulièrement dynamique. Avec des institutions comme Mila, l'IVADO et une politique nationale en IA publiée dès 2019, la province a posé les bases d'une transformation numérique ambitieuse. Les organismes publics bénéficient désormais d'un cadre réglementaire clair — notamment avec la Loi 25 sur la protection des renseignements personnels — pour déployer des solutions d'IA responsables." },
      { h: "Les cas d'usage les plus prometteurs", p: "Parmi les applications concrètes déjà déployées ou en cours d'expérimentation, on retrouve : la gestion intelligente des files d'attente dans les services de santé, les chatbots multilingues pour les portails citoyens, l'analyse prédictive pour l'entretien des infrastructures, et le traitement automatisé des demandes administratives. AttenteZéro, développé par CivicAI, illustre précisément cette approche : un répertoire de services communautaires propulsé par l'IA, gratuit pour les citoyens et financé par un modèle B2G." },
      { h: "Les défis à surmonter", p: "Plusieurs obstacles freinent encore l'adoption de l'IA dans le secteur public. La question de la transparence algorithmique est centrale : les citoyens ont le droit de comprendre comment les décisions qui les concernent sont prises. La protection des données sensibles, la gestion du changement au sein des équipes, et le besoin de compétences numériques spécialisées représentent également des enjeux majeurs." },
      { h: "Notre approche chez CivicAI", p: "Nous croyons que l'IA dans le secteur public doit être conçue avec un principe fondamental : la technologie au service de l'humain, pas l'inverse. Chaque solution que nous développons intègre des mécanismes d'explicabilité, respecte la confidentialité des données et privilégie l'accessibilité pour tous les citoyens, incluant les populations les plus vulnérables. C'est cette philosophie qui guide AttenteZéro depuis son lancement." },
    ],
  },
  {
    slug: "developpement-web-2026",
    category: "Développement web",
    date: "28 avril 2026",
    readTime: "5 min",
    title: "Développement web en 2026 : ce qui a vraiment changé",
    excerpt: "De React Server Components à l'IA générative intégrée aux outils de développement, le paysage du développement web évolue à une vitesse vertigineuse. Voici notre lecture des tendances qui comptent vraiment.",
    sections: [
      { p: "En quelques années, le développement web a connu une transformation profonde. Si HTML, CSS et JavaScript restent les fondations, les pratiques, les outils et les attentes ont radicalement évolué. En 2026, construire un site web « moderne » signifie bien plus que produire quelques pages HTML." },
      { h: "La performance, un impératif non négociable", p: "Les Core Web Vitals de Google ont définitivement imposé la performance comme critère de qualité incontournable. LCP, INP, CLS — ces métriques déterminent non seulement l'expérience utilisateur, mais aussi le positionnement dans les résultats de recherche. Les équipes qui ignorent encore ces indicateurs se retrouvent pénalisées deux fois : par leurs utilisateurs et par les moteurs de recherche." },
      { h: "L'IA générative au cœur du workflow", p: "GitHub Copilot, Cursor, v0 par Vercel... les outils d'assistance au développement par IA ont changé la productivité des équipes. On observe des gains de 30 à 50 % sur les tâches répétitives — génération de tests, documentation, migrations de code. Chez CivicAI, nous intégrons ces outils dans notre workflow quotidien, tout en maintenant un contrôle strict sur la qualité et la sécurité du code produit." },
      { h: "TypeScript : la norme, enfin", p: "Il y a cinq ans, TypeScript était encore perçu comme un choix « avancé ». En 2026, développer en JavaScript vanilla pour un projet professionnel commence à sembler risqué. L'ensemble de notre stack — API Express, app React, Expo mobile — est intégralement typé. La fiabilité gagnée en vaut largement l'investissement initial." },
      { h: "L'accessibilité, de l'obligation à l'avantage compétitif", p: "Les nouvelles réglementations européennes (European Accessibility Act) et canadiennes poussent les organisations à prendre l'accessibilité au sérieux. Mais au-delà de la conformité légale, un site accessible convertit mieux : il est plus lisible, plus navigable, plus rapide. C'est un avantage compétitif souvent sous-estimé que nous intégrons systématiquement dans nos projets." },
    ],
  },
  {
    slug: "modele-b2g",
    category: "B2G",
    date: "10 avril 2026",
    readTime: "7 min",
    title: "Le modèle B2G : quand les gouvernements deviennent des clients technologiques",
    excerpt: "Le modèle Business-to-Government (B2G) représente une opportunité considérable pour les entreprises technologiques québécoises. Découvrez comment fonctionne ce marché, ses particularités et pourquoi CivicAI l'a choisi pour AttenteZéro.",
    sections: [
      { p: "Le marché des technologies pour le secteur public — connu sous l'acronyme B2G (Business-to-Government) — représente des milliards de dollars au Canada chaque année. Pourtant, il reste largement méconnu des entrepreneurs technologiques, souvent intimidés par sa complexité perçue. À tort." },
      { h: "Qu'est-ce que le modèle B2G ?", p: "Le B2G désigne les échanges commerciaux entre une entreprise privée et des entités gouvernementales : municipalités, ministères, organismes publics, établissements de santé ou d'éducation. Contrairement au B2B ou au B2C, les processus d'achat sont encadrés par des règles de transparence et d'appels d'offres qui visent à garantir l'équité et l'utilisation responsable des fonds publics." },
      { h: "Un marché stable et prévisible", p: "L'un des atouts majeurs du B2G est sa stabilité. Les contrats gouvernementaux sont généralement pluriannuels, les cycles de renouvellement prévisibles, et les risques d'impayés quasi inexistants. Pour une entreprise en croissance, c'est une base de revenus récurrents particulièrement solide, bien différente de la volatilité du marché privé." },
      { h: "Le modèle d'AttenteZéro : un cas d'école", p: "AttenteZéro illustre parfaitement l'approche B2G de CivicAI. L'application est entièrement gratuite pour les citoyens — c'est notre engagement social. Le modèle économique repose sur la vente de tableaux de bord analytiques anonymisés aux administrations publiques : municipalités, CISSS, ministères. Ces données agrégées leur permettent de mieux comprendre les besoins de leur population et d'optimiser leur offre de services. Win-win : les citoyens obtiennent un outil gratuit, les administrations obtiennent des données actionnables." },
      { h: "Comment se lancer dans le B2G ?", p: "Notre conseil principal : commencez par comprendre les processus d'achat publics de votre province. Au Québec, le Système électronique d'appel d'offres (SEAO) centralise les appels d'offres publics. Identifiez les problèmes que vous pouvez résoudre, construisez des preuves de concept, et approchez d'abord les petites municipalités ou organismes — leurs cycles de décision sont plus courts. La clé : la patience et la persévérance. Le B2G prend du temps, mais une fois établi, les relations sont durables." },
    ],
  },
];

export const BLOG_ARTICLES_EN = [
  {
    slug: "ia-secteur-public",
    category: "AI & Public",
    date: "May 12, 2026",
    readTime: "6 min",
    title: "AI in the Public Sector: Opportunities and Challenges",
    excerpt: "How Canadian public administrations can leverage artificial intelligence to improve their citizen services, while respecting transparency requirements and data protection obligations.",
    sections: [
      { p: "Artificial intelligence is no longer the exclusive domain of large tech companies. Today, public administrations — municipalities, ministries, and parapublic organizations — find themselves at a decisive crossroads: integrate AI to better serve their citizens, or risk falling behind ever-growing expectations." },
      { h: "A Favorable Context in Quebec", p: "Quebec has a particularly dynamic AI ecosystem. With institutions like Mila, IVADO and a national AI policy published as early as 2019, the province laid the groundwork for an ambitious digital transformation. Public organizations now benefit from a clear regulatory framework — particularly with Law 25 on personal information protection — to deploy responsible AI solutions." },
      { h: "The Most Promising Use Cases", p: "Among the concrete applications already deployed or being piloted: intelligent queue management in healthcare services, multilingual chatbots for citizen portals, predictive analytics for infrastructure maintenance, and automated processing of administrative requests. AttenteZéro, developed by CivicAI, precisely illustrates this approach: an AI-powered directory of community services, free for citizens and financed by a B2G model." },
      { h: "Challenges to Overcome", p: "Several obstacles still slow AI adoption in the public sector. The question of algorithmic transparency is central: citizens have the right to understand how decisions that affect them are made. Protecting sensitive data, managing organizational change, and the need for specialized digital skills are also major challenges." },
      { h: "Our Approach at CivicAI", p: "We believe that AI in the public sector must be designed with one fundamental principle: technology at the service of people, not the other way around. Every solution we develop incorporates explainability mechanisms, respects data privacy, and prioritizes accessibility for all citizens, including the most vulnerable populations. This philosophy has guided AttenteZéro since its launch." },
    ],
  },
  {
    slug: "developpement-web-2026",
    category: "Web Development",
    date: "April 28, 2026",
    readTime: "5 min",
    title: "Web Development in 2026: What Has Really Changed",
    excerpt: "From React Server Components to AI-powered dev tools, the web development landscape is evolving at a dizzying pace. Here is our take on the trends that truly matter.",
    sections: [
      { p: "In just a few years, web development has undergone a profound transformation. While HTML, CSS and JavaScript remain the foundations, practices, tools, and expectations have radically evolved. In 2026, building a 'modern' website means much more than producing a few HTML pages." },
      { h: "Performance: A Non-Negotiable Imperative", p: "Google's Core Web Vitals have definitively established performance as an essential quality criterion. LCP, INP, CLS — these metrics determine not only user experience, but also search engine rankings. Teams that still ignore these indicators find themselves penalized twice: by their users and by search engines." },
      { h: "Generative AI at the Heart of the Workflow", p: "GitHub Copilot, Cursor, Vercel's v0... AI-powered development assistance tools have changed team productivity. We see 30-50% gains on repetitive tasks — test generation, documentation, code migrations. At CivicAI, we integrate these tools into our daily workflow, while maintaining strict control over code quality and security." },
      { h: "TypeScript: Finally the Standard", p: "Five years ago, TypeScript was still seen as an 'advanced' choice. In 2026, developing in vanilla JavaScript for a professional project is starting to seem risky. Our entire stack — Express API, React app, Expo mobile — is fully typed. The reliability gained is well worth the initial investment." },
      { h: "Accessibility: From Obligation to Competitive Advantage", p: "New European (European Accessibility Act) and Canadian regulations are pushing organizations to take accessibility seriously. But beyond legal compliance, an accessible site converts better: it is more readable, more navigable, faster. It is a competitive advantage that is often underestimated, and one we systematically integrate into all our projects." },
    ],
  },
  {
    slug: "modele-b2g",
    category: "B2G",
    date: "April 10, 2026",
    readTime: "7 min",
    title: "The B2G Model: When Governments Become Technology Clients",
    excerpt: "The Business-to-Government (B2G) model represents a considerable opportunity for Quebec technology companies. Discover how this market works, its particularities, and why CivicAI chose it for AttenteZéro.",
    sections: [
      { p: "The public sector technology market — known by the acronym B2G (Business-to-Government) — represents billions of dollars in Canada every year. Yet it remains largely unknown to tech entrepreneurs, who are often intimidated by its perceived complexity. Wrongly so." },
      { h: "What is the B2G Model?", p: "B2G refers to commercial exchanges between a private company and government entities: municipalities, ministries, public organizations, health or education institutions. Unlike B2B or B2C, procurement processes are governed by transparency rules and tender calls that aim to ensure fairness and responsible use of public funds." },
      { h: "A Stable and Predictable Market", p: "One of B2G's major assets is its stability. Government contracts are generally multi-year, renewal cycles are predictable, and the risk of non-payment is almost non-existent. For a growing company, this provides a particularly solid base of recurring revenue, very different from the volatility of the private market." },
      { h: "AttenteZéro's Model: A Case Study", p: "AttenteZéro perfectly illustrates CivicAI's B2G approach. The application is entirely free for citizens — that is our social commitment. The business model is based on selling anonymized analytical dashboards to public administrations: municipalities, health authorities, ministries. This aggregated data allows them to better understand their population's needs and optimize their service offering. Win-win: citizens get a free tool, administrations get actionable data." },
      { h: "How to Enter the B2G Market?", p: "Our main advice: start by understanding your province's public procurement processes. In Quebec, the Electronic Procurement System (SEAO) centralizes public tender calls. Identify the problems you can solve, build proofs of concept, and approach smaller municipalities or organizations first — their decision cycles are shorter. The key: patience and perseverance. B2G takes time, but once established, the relationships are lasting." },
    ],
  },
];

export const T = {
  fr: {
    nav: { home: "Accueil", services: "Services", products: "Produits", blog: "Blog", contact: "Contact", cta: "Consultation gratuite" },
    hero_tag: "IA · Bien commun · Québec, Canada",
    hero_title_1: "Technologie au service",
    hero_title_2: "de vos idées.",
    hero_sub: "CivicAI conçoit des solutions numériques intelligentes pour les entreprises, organisations et administrations publiques — partout au Canada.",
    hero_cta: "Consultation gratuite — 30 min",
    hero_cta2: "Voir nos services",
    trust_stats: [
      { value: "7 957", label: "services communautaires\nrépertoriés au Québec" },
      { value: "5", label: "langues supportées\nFR · EN · ES · AR · HT" },
      { value: "100 %", label: "données hébergées\nau Canada" },
      { value: "Gratuit", label: "pour les citoyens\nmodèle B2G" },
    ],
    trust_badges: [
      { icon: "🏢", label: "Entreprise québécoise", sub: "NEQ 2280791601" },
      { icon: "🔒", label: "Conforme Loi 25 QC", sub: "Protection des données" },
      { icon: "🌐", label: "Multilingue", sub: "FR · EN · ES · AR · HT" },
      { icon: "🤝", label: "Sans engagement", sub: "1re rencontre gratuite" },
    ],
    impact_stats: [
      { value: "80%", label: "des PME sans outil numérique", sub: "Opportunité de transformation" },
      { value: "6h", label: "économisées par semaine", sub: "En moyenne après déploiement" },
      { value: "60j", label: "pour voir un ROI", sub: "Retour sur investissement" },
    ],
    results_tag: "Résultats concrets",
    results_title: "Ce que nos clients obtiennent",
    results_sub: "Des exemples réels de transformations réalisées avec CivicAI.",
    results_items: [
      { icon: "🏗", sector: "Entreprise de construction", problem: "Gestion de 5 chantiers simultanés avec Excel et papier — heures perdues chaque semaine.", solution: "Tableau de bord unique · Rapports terrain mobile · Feuilles de temps automatisées", metric: "8h/sem. économisées" },
      { icon: "🏢", sector: "Promoteur immobilier", problem: "Coordination impossible entre bureau, terrain, sous-traitants et permis.", solution: "Plateforme centralisée · Conformité réglementaire automatique · Portail client inclus", metric: "Zéro oubli de permis" },
      { icon: "🛒", sector: "PME commerciale", problem: "Aucune visibilité sur les ventes et les clients. Suivi 100% manuel.", solution: "CRM sur mesure · Tableau de bord des ventes · Relances automatiques clients", metric: "+60% de suivi client" },
      { icon: "🌐", sector: "Organisme communautaire", problem: "Site web désuet, processus manuels et perte de membres faute de communication.", solution: "Site web moderne · Automatisation des communications · Gestion des membres", metric: "+40% d'engagement" },
    ],
    automation_tag: "Automatisation",
    automation_title: "Transformez vos processus en flux intelligents",
    automation_sub: "Vos processus sur papier et Excel coûtent du temps et de l'argent. Nous les transformons en solutions numériques modernes, accessibles depuis votre téléphone.",
    automation_items: [
      { icon: "📝", title: "Formulaires automatisés", desc: "Transformez vos formulaires papier en formulaires numériques envoyés, traités et archivés automatiquement.", examples: ["Demandes de service", "Rapports d'inspection", "Bons de travail"] },
      { icon: "⚙️", title: "Flux de travail", desc: "Créez des séquences automatiques : réception → notification → traitement → confirmation → archivage.", examples: ["Approbation de devis", "Suivi de commandes", "Relances clients"] },
      { icon: "🔗", title: "Intégration de systèmes", desc: "Connectez vos outils existants pour éliminer la double saisie et les erreurs de transfert d'information.", examples: ["CRM ↔ comptabilité", "Formulaires ↔ base de données", "App mobile ↔ bureau"] },
      { icon: "🔔", title: "Notifications & alertes", desc: "Recevez les bonnes informations au bon moment — sans avoir à aller les chercher vous-même.", examples: ["Alertes d'échéance", "Rappels automatiques", "Rapports programmés"] },
    ],
    founder: {
      name: "Edem Gnagblodjro",
      title: "Fondateur & CEO",
      company: "CivicAI",
      phone: "905 809-7798",
      availability: "Disponible 7j/7",
      cta_phone: "Appeler directement",
      cta_email: "Écrire un courriel",
      neq: "NEQ 2280791601",
      based: "Basé au Canada · Sert partout",
    },
    why_tag: "Pourquoi CivicAI",
    why_title: "La technologie qui travaille pour vous",
    why_sub: "Nous ne vendons pas de logiciels. Nous construisons les outils qui transforment votre façon de travailler.",
    why_items: [
      { icon: "⚡", title: "Rapide à déployer", desc: "Nos solutions sont prêtes en semaines, pas en années. Vous voyez les résultats rapidement." },
      { icon: "🎯", title: "Conçu pour vous", desc: "Chaque solution est 100 % sur mesure, adaptée à vos processus et votre réalité." },
      { icon: "🔒", title: "Sécurisé & conforme", desc: "Données hébergées au Canada, conformité Loi 25 QC, chiffrement TLS/SSL intégré." },
      { icon: "📈", title: "Résultats mesurables", desc: "KPIs définis dès le départ, tableaux de bord en temps réel, ROI transparent." },
    ],
    services_tag: "Nos services",
    services_title: "Ce que nous faisons",
    services_sub: "Des solutions technologiques complètes, de l'automatisation IA au marketing digital.",
    services_cta: "Voir tous nos services",
    products_tag: "Nos produits",
    products_title: "Solutions prêtes à déployer",
    products_sub: "Des produits CivicAI disponibles dès maintenant pour répondre à vos besoins.",
    flagship_tag: "Produit citoyen phare",
    flagship_name: "AttenteZéro",
    flagship_desc: "Un répertoire intelligent de services communautaires propulsé par l'IA. Gratuit pour tous les citoyens du Québec.",
    flagship_stats: ["7 957", "services actifs", "5", "langues", "100%", "gratuit"],
    flagship_ios: "App Store",
    flagship_android: "Google Play",
    erp_tag: "ERP · Secteur construction",
    erp_name: "ConstructPro ERP",
    erp_desc: "Un ERP moderne dédié aux entreprises de construction : gestion de projets, soumissions, équipes et finances en un seul outil.",
    erp_features: ["Gestion de projets & chantiers", "Soumissions & estimations", "Suivi d'équipes & sous-traitants", "Facturation & finances", "Rapports & tableaux de bord"],
    erp_cta: "Consultation gratuite",
    cta_banner_title: "Prêt à transformer votre organisation ?",
    cta_banner_sub: "Consultation gratuite de 30 minutes, sans engagement. Réponse en 24h.",
    cta_banner_btn: "Consultation gratuite — 30 min",
    how_tag: "Notre processus",
    how_title: "Comment démarrer ensemble",
    how_sub: "Un processus simple et transparent en 4 étapes pour passer de l'idée au lancement.",
    steps: [
      { n: "01", icon: <Search className="w-6 h-6" />, title: "Consultation gratuite", desc: "30 min pour comprendre vos besoins, vos défis et vos objectifs. Sans engagement.", time: "Jour 1" },
      { n: "02", icon: <Target className="w-6 h-6" />, title: "Proposition sur mesure", desc: "Vous recevez une solution claire et adaptée à votre réalité sous 3 à 5 jours ouvrables.", time: "3–5 jours" },
      { n: "03", icon: <Palette className="w-6 h-6" />, title: "Développement & tests", desc: "Notre équipe développe votre solution avec des points d'avancement réguliers. Vous êtes impliqué à chaque étape.", time: "2–8 semaines" },
      { n: "04", icon: <Rocket className="w-6 h-6" />, title: "Lancement & formation", desc: "Déploiement, formation de votre équipe et support post-lancement. Opérationnel en moins de 30 jours.", time: "< 30 jours" },
    ],
    faqs: [
      { q: "Quels sont vos délais de livraison ?", a: "Selon la complexité du projet, nos délais vont de 2 semaines (site web simple) à 6 mois (solution IA sur mesure). Nous établissons un calendrier précis lors de la rencontre initiale." },
      { q: "Comment garantissez-vous la sécurité des données ?", a: "Toutes nos solutions respectent la Loi 25 du Québec : chiffrement TLS/SSL, données hébergées au Canada, anonymisation systématique des données sensibles." },
      { q: "Travaillez-vous avec des organismes à but non lucratif ?", a: "Oui. Nous proposons des tarifs adaptés aux OBNL et organismes communautaires. AttenteZéro en est le meilleur exemple — entièrement gratuit pour les citoyens." },
      { q: "Proposez-vous du support après la livraison ?", a: "Absolument. Chaque projet inclut une période de support post-lancement, et nous proposons des contrats de maintenance et d'évolution." },
      { q: "Comment se déroule la première rencontre ?", a: "La première rencontre est gratuite et sans engagement. Nous découvrons vos besoins et vous repartirez avec une proposition préliminaire sous 48h." },
    ],
    contact_tag: "Contact",
    contact_title: "Parlons de votre projet",
    contact_sub: "Entreprise, organisme ou administration publique ? Décrivez-nous votre projet.",
    form_name: "Nom complet",
    form_org: "Organisation",
    form_email: "Adresse courriel",
    form_phone: "Téléphone (optionnel)",
    form_service: "Service souhaité",
    form_service_options: ["IA & Automatisation", "Solutions sur mesure", "Optimisation IA", "Développement web", "Marketing digital", "ConstructPro ERP", "Autre"],
    form_msg: "Décrivez votre projet...",
    form_send: "Envoyer la demande",
    form_success: "Merci ! Nous vous répondrons sous 48h.",
    footer_tagline: "TECHNOLOGIE AU SERVICE DE VOS IDÉES",
    footer_copy: "© 2026 CivicAI — NEQ 2280791601 — Québec, Canada",
    footer_links_services: "Services",
    footer_links_products: "Produits",
    footer_links_legal: "Légal",
    footer_privacy: "Politique de confidentialité",
    footer_about: "À propos",
    footer_links_blog: "Ressources",
    footer_blog: "Blog",
    testimonials_tag: "Ils nous font confiance",
    testimonials_title: "Ce que disent nos clients",
    testimonials_sub: "Organisations publiques, OBNL et entreprises — voici leurs retours.",
    testimonials: [
      { quote: "CivicAI a livré en 6 semaines ce que nos prestataires habituels estimaient à 6 mois. L'outil de suivi d'interventions a immédiatement réduit notre charge administrative.", name: "Marie-Claude Tremblay", role: "Directrice des services aux citoyens", org: "" },
      { quote: "AttenteZéro a transformé notre façon d'orienter les usagers en situation de crise. En un seul écran, nos travailleurs sociaux trouvent l'hébergement d'urgence disponible dans un rayon de 5 km.", name: "Jean-François Gagnon", role: "Responsable des services intégrés", org: "" },
      { quote: "Nous avons confié à CivicAI la refonte complète de notre portail organisationnel. Résultat : notre taux de complétion des demandes de subvention est passé de 61 % à 89 %.", name: "Sophie Beauchamp", role: "Directrice générale", org: "" },
      { quote: "Le tableau de bord B2G que CivicAI nous a fourni nous permet enfin de croiser les besoins déclarés et les services disponibles sur notre territoire. Une donnée qu'on cherchait depuis des années.", name: "Patrick Leblanc", role: "Directeur de la transformation numérique", org: "" },
    ],
    blog_tag: "Blog & Ressources",
    blog_title: "Insights & perspectives",
    blog_sub: "Nos réflexions sur l'IA, le développement web et la technologie au service du secteur public.",
    blog_read_more: "Lire l'article",
    blog_back: "Retour au blog",
    blog_min_read: "min de lecture",
    blog_cta: "Voir tous les articles",
    blog_articles: BLOG_ARTICLES_FR,
    slides: SLIDES_FR,
  },
  en: {
    nav: { home: "Home", services: "Services", products: "Products", blog: "Blog", contact: "Contact", cta: "Free consultation" },
    hero_tag: "AI · Public Good · Quebec, Canada",
    hero_title_1: "Technology at the service",
    hero_title_2: "of your ideas.",
    hero_sub: "CivicAI designs intelligent digital solutions for businesses, organizations, and public administrations — across Canada.",
    hero_cta: "Free consultation — 30 min",
    hero_cta2: "See our services",
    trust_stats: [
      { value: "7,957", label: "community services\nlisted in Quebec" },
      { value: "5", label: "supported languages\nFR · EN · ES · AR · HT" },
      { value: "100%", label: "data hosted\nin Canada" },
      { value: "Free", label: "for citizens\nB2G model" },
    ],
    trust_badges: [
      { icon: "🏢", label: "Quebec company", sub: "NEQ 2280791601" },
      { icon: "🔒", label: "Law 25 QC compliant", sub: "Data protection" },
      { icon: "🌐", label: "Multilingual", sub: "FR · EN · ES · AR · HT" },
      { icon: "🤝", label: "No commitment", sub: "Free first meeting" },
    ],
    impact_stats: [
      { value: "80%", label: "of SMBs have no digital tools", sub: "Transformation opportunity" },
      { value: "6h", label: "saved per week on average", sub: "After deployment" },
      { value: "60d", label: "to see an ROI", sub: "Return on investment" },
    ],
    results_tag: "Real results",
    results_title: "What our clients achieve",
    results_sub: "Real transformation examples delivered with CivicAI.",
    results_items: [
      { icon: "🏗", sector: "Construction company", problem: "Managing 5 simultaneous job sites with Excel and paper — hours lost every week.", solution: "Single dashboard · Mobile field reports · Automated timesheets", metric: "8h/week saved" },
      { icon: "🏢", sector: "Real estate developer", problem: "Impossible coordination between office, field, subcontractors, and permits.", solution: "Centralized platform · Automatic regulatory compliance · Client portal included", metric: "Zero missed permits" },
      { icon: "🛒", sector: "Commercial SMB", problem: "No visibility on sales and clients. 100% manual tracking.", solution: "Custom CRM · Sales dashboard · Automatic client follow-ups", metric: "+60% client follow-up" },
      { icon: "🌐", sector: "Community organization", problem: "Outdated website, manual processes and loss of members due to poor communication.", solution: "Modern website · Communication automation · Member management", metric: "+40% engagement" },
    ],
    automation_tag: "Automation",
    automation_title: "Transform your processes into smart workflows",
    automation_sub: "Your paper and Excel processes cost time and money. We turn them into modern digital solutions, accessible from your phone.",
    automation_items: [
      { icon: "📝", title: "Automated forms", desc: "Transform your paper forms into digital forms that are sent, processed, and archived automatically.", examples: ["Service requests", "Inspection reports", "Work orders"] },
      { icon: "⚙️", title: "Automated workflows", desc: "Create automatic sequences: receipt → notification → processing → confirmation → archiving.", examples: ["Quote approval", "Order tracking", "Client follow-ups"] },
      { icon: "🔗", title: "System integration", desc: "Connect your existing tools to eliminate double entry and information transfer errors.", examples: ["CRM ↔ accounting", "Forms ↔ database", "Mobile app ↔ desktop"] },
      { icon: "🔔", title: "Notifications & alerts", desc: "Receive the right information at the right time — without having to go look for it yourself.", examples: ["Deadline alerts", "Automatic reminders", "Scheduled reports"] },
    ],
    founder: {
      name: "Edem Gnagblodjro",
      title: "Founder & CEO",
      company: "CivicAI",
      phone: "905 809-7798",
      availability: "Available 7 days/week",
      cta_phone: "Call directly",
      cta_email: "Send an email",
      neq: "NEQ 2280791601",
      based: "Based in Canada · Serves everywhere",
    },
    why_tag: "Why CivicAI",
    why_title: "Technology that works for you",
    why_sub: "We don't sell software. We build the tools that transform how you work.",
    why_items: [
      { icon: "⚡", title: "Fast to deploy", desc: "Our solutions are ready in weeks, not years. You see results quickly." },
      { icon: "🎯", title: "Built for you", desc: "Every solution is 100% custom, adapted to your processes and reality." },
      { icon: "🔒", title: "Secure & compliant", desc: "Data hosted in Canada, Law 25 QC compliance, built-in TLS/SSL encryption." },
      { icon: "📈", title: "Measurable results", desc: "KPIs defined from day one, real-time dashboards, transparent ROI." },
    ],
    services_tag: "Our services",
    services_title: "What we do",
    services_sub: "Complete technology solutions, from AI automation to digital marketing.",
    services_cta: "See all services",
    products_tag: "Our products",
    products_title: "Ready-to-deploy solutions",
    products_sub: "CivicAI products available now to meet your needs.",
    flagship_tag: "Flagship civic product",
    flagship_name: "AttenteZéro",
    flagship_desc: "An AI-powered directory of community services — free for all citizens of Quebec.",
    flagship_stats: ["7,957", "active services", "5", "languages", "100%", "free"],
    flagship_ios: "App Store",
    flagship_android: "Google Play",
    erp_tag: "ERP · Construction sector",
    erp_name: "ConstructPro ERP",
    erp_desc: "A modern ERP dedicated to construction companies: project management, bids, teams, and finances in one tool.",
    erp_features: ["Project & site management", "Bids & estimates", "Team & subcontractor tracking", "Invoicing & finances", "Reports & dashboards"],
    erp_cta: "Free consultation",
    cta_banner_title: "Ready to transform your organization?",
    cta_banner_sub: "Free 30-minute consultation, no commitment. Response within 24h.",
    cta_banner_btn: "Free consultation — 30 min",
    how_tag: "Our process",
    how_title: "How to get started",
    how_sub: "A simple, transparent 4-step process to go from idea to launch.",
    steps: [
      { n: "01", icon: <Search className="w-6 h-6" />, title: "Free consultation", desc: "30 minutes to understand your needs, challenges, and goals. No commitment required.", time: "Day 1" },
      { n: "02", icon: <Target className="w-6 h-6" />, title: "Custom proposal", desc: "You receive a clear solution tailored to your reality within 3 to 5 business days.", time: "3–5 days" },
      { n: "03", icon: <Palette className="w-6 h-6" />, title: "Development & testing", desc: "Our team builds your custom solution with regular progress updates and your feedback integrated.", time: "2–8 weeks" },
      { n: "04", icon: <Rocket className="w-6 h-6" />, title: "Launch & training", desc: "Deployment, team training, and post-launch support. Operational in under 30 days.", time: "< 30 days" },
    ],
    faqs: [
      { q: "What are your delivery timelines?", a: "Depending on complexity, our timelines range from 2 weeks (simple website) to 6 months (custom AI solution). We set a precise schedule at the initial meeting." },
      { q: "How do you guarantee data security?", a: "All our solutions comply with Quebec's Law 25: TLS/SSL encryption, data hosted in Canada, systematic anonymization of sensitive data." },
      { q: "Do you work with non-profit organizations?", a: "Yes. We offer adapted pricing for non-profits and community organizations. AttenteZéro is the best example — entirely free for citizens." },
      { q: "Do you offer post-delivery support?", a: "Absolutely. Every project includes a post-launch support period, and we offer maintenance and evolution contracts." },
      { q: "How does the first meeting work?", a: "The first meeting is free and without commitment. We discover your needs and you'll receive a preliminary proposal within 48 hours." },
    ],
    contact_tag: "Contact",
    contact_title: "Let's talk about your project",
    contact_sub: "Business, organization, or public administration? Tell us about your project.",
    form_name: "Full name",
    form_org: "Organization",
    form_email: "Email address",
    form_phone: "Phone (optional)",
    form_service: "Desired service",
    form_service_options: ["AI & Automation", "Custom solutions", "AI Optimization", "Web development", "Digital marketing", "ConstructPro ERP", "Other"],
    form_msg: "Describe your project...",
    form_send: "Send request",
    form_success: "Thank you! We'll get back to you within 48h.",
    footer_tagline: "TECHNOLOGY AT THE SERVICE OF YOUR IDEAS",
    footer_copy: "© 2026 CivicAI — NEQ 2280791601 — Quebec, Canada",
    footer_links_services: "Services",
    footer_links_products: "Products",
    footer_links_legal: "Legal",
    footer_privacy: "Privacy policy",
    footer_about: "About",
    footer_links_blog: "Resources",
    footer_blog: "Blog",
    testimonials_tag: "Trusted by organizations",
    testimonials_title: "What our clients say",
    testimonials_sub: "Public organizations, non-profits, and businesses — here is their feedback.",
    testimonials: [
      { quote: "CivicAI delivered in 6 weeks what our usual vendors estimated at 6 months. The intervention tracking tool immediately reduced our administrative burden.", name: "Marie-Claude Tremblay", role: "Director of Citizen Services", org: "" },
      { quote: "AttenteZéro transformed how we direct people in crisis situations. In a single screen, our social workers find available emergency housing within a 5 km radius.", name: "Jean-François Gagnon", role: "Integrated Services Manager", org: "" },
      { quote: "We entrusted CivicAI with the complete overhaul of our organizational portal. Result: our grant application completion rate went from 61% to 89%.", name: "Sophie Beauchamp", role: "Executive Director", org: "" },
      { quote: "The B2G dashboard CivicAI provided finally allows us to cross-reference declared needs with available services in our territory. Data we had been looking for years.", name: "Patrick Leblanc", role: "Director of Digital Transformation", org: "" },
    ],
    blog_tag: "Blog & Resources",
    blog_title: "Insights & perspectives",
    blog_sub: "Our thoughts on AI, web development and technology at the service of the public sector.",
    blog_read_more: "Read article",
    blog_back: "Back to blog",
    blog_min_read: "min read",
    blog_cta: "See all articles",
    blog_articles: BLOG_ARTICLES_EN,
    slides: SLIDES_EN,
  },
} as const;

export type TType = typeof T.fr;

interface LangContextType {
  lang: Lang;
  setLang: (l: Lang) => void;
}

const LangContext = createContext<LangContextType>({ lang: "fr", setLang: () => {} });

export function LangProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Lang>("fr");
  return <LangContext.Provider value={{ lang, setLang }}>{children}</LangContext.Provider>;
}

export function useLang() {
  return useContext(LangContext);
}
