import { createContext, useContext, useState, type ReactNode } from "react";
import { Bot, Settings, Rocket, Laptop, TrendingUp, Search, Palette, Target } from "lucide-react";

export type Lang = "fr" | "en";

const BASE = import.meta.env.BASE_URL;

export const SLIDES_FR = [
  {
    badge: "IA & Automatisation",
    title: "L'IA au service de votre entreprise",
    punch: "Travaillez plus intelligemment.",
    desc: "Nous aidons les entreprises à automatiser leurs tâches et à exploiter l'IA pour gagner en productivité.",
    features: ["Outils de gestion sur mesure", "Automatisation avec l'IA", "Optimisation des outils existants", "Tableaux de bord intelligents"],
    image: `${BASE}slides/slide-ai.png`,
    gradient: "from-blue-950/95 via-blue-900/75 to-blue-800/20",
    icon: <Bot className="w-7 h-7" />,
  },
  {
    badge: "Solutions sur mesure",
    title: "Vos idées. Nos solutions technologiques.",
    punch: "Des outils performants pour avancer vite.",
    desc: "Solutions personnalisées pour gérer vos projets, clients, finances et analyses en un seul endroit.",
    features: ["Gestion de projets & tâches", "CRM & gestion clients", "Facturation & paiements", "Solutions 100 % personnalisées"],
    image: `${BASE}slides/slide-custom.png`,
    gradient: "from-indigo-950/95 via-indigo-900/75 to-indigo-800/20",
    icon: <Settings className="w-7 h-7" />,
  },
  {
    badge: "Optimisation IA",
    title: "Optimiser. Automatiser. Propulser.",
    punch: "Votre partenaire technologique de confiance.",
    desc: "Nous optimisons vos outils existants avec l'IA pour des résultats concrets et mesurables.",
    features: ["Automatisation intelligente", "Gain de temps et d'efficacité", "Meilleures décisions", "Croissance durable"],
    image: `${BASE}slides/slide-optimize.png`,
    gradient: "from-slate-950/95 via-slate-900/75 to-slate-800/20",
    icon: <Rocket className="w-7 h-7" />,
  },
  {
    badge: "Développement web",
    title: "Sites web modernes pour entreprises ambitieuses.",
    punch: "Design, performance et UX au cœur de tout.",
    desc: "Nous concevons des sites web sur mesure qui reflètent votre marque et convertissent vos visiteurs.",
    features: ["Sites web sur mesure", "Design réactif & moderne", "SEO & performance", "Maintenance & support"],
    image: `${BASE}slides/slide-web.png`,
    gradient: "from-cyan-950/95 via-cyan-900/75 to-cyan-800/20",
    icon: <Laptop className="w-7 h-7" />,
  },
  {
    badge: "Marketing digital",
    title: "Digital. Stratégie. Croissance.",
    punch: "Ensemble, propulsons votre entreprise.",
    desc: "Nous vous aidons à bâtir votre présence en ligne et atteindre vos objectifs avec une stratégie complète.",
    features: ["Stratégie digitale", "Gestion des réseaux sociaux", "Publicité en ligne (SEA & Social Ads)", "Contenu & image de marque"],
    image: `${BASE}slides/slide-marketing.png`,
    gradient: "from-blue-950/95 via-blue-900/75 to-blue-800/20",
    icon: <TrendingUp className="w-7 h-7" />,
  },
];

export const SLIDES_EN = [
  {
    badge: "AI & Automation",
    title: "AI at the service of your business",
    punch: "Work smarter. Grow faster.",
    desc: "We help businesses automate tasks and leverage AI to boost productivity.",
    features: ["Custom management tools", "AI automation", "Optimization of existing tools", "Smart dashboards"],
    image: `${BASE}slides/slide-ai.png`,
    gradient: "from-blue-950/95 via-blue-900/75 to-blue-800/20",
    icon: <Bot className="w-7 h-7" />,
  },
  {
    badge: "Custom solutions",
    title: "Your ideas. Our technology.",
    punch: "High-performance tools to move fast.",
    desc: "Customized solutions to manage your projects, clients, finances, and analytics in one place.",
    features: ["Project & task management", "CRM & client management", "Invoicing & payments", "100% custom solutions"],
    image: `${BASE}slides/slide-custom.png`,
    gradient: "from-indigo-950/95 via-indigo-900/75 to-indigo-800/20",
    icon: <Settings className="w-7 h-7" />,
  },
  {
    badge: "AI Optimization",
    title: "Optimize. Automate. Propel.",
    punch: "Your trusted technology partner.",
    desc: "We optimize your existing tools with AI for concrete, measurable results.",
    features: ["Intelligent automation", "Time savings & efficiency", "Better decisions", "Sustainable growth"],
    image: `${BASE}slides/slide-optimize.png`,
    gradient: "from-slate-950/95 via-slate-900/75 to-slate-800/20",
    icon: <Rocket className="w-7 h-7" />,
  },
  {
    badge: "Web development",
    title: "Modern websites for ambitious businesses.",
    punch: "Design, performance and UX at the core.",
    desc: "We design custom websites that reflect your brand and convert visitors into customers.",
    features: ["Custom websites", "Responsive & modern design", "SEO & performance", "Maintenance & support"],
    image: `${BASE}slides/slide-web.png`,
    gradient: "from-cyan-950/95 via-cyan-900/75 to-cyan-800/20",
    icon: <Laptop className="w-7 h-7" />,
  },
  {
    badge: "Digital marketing",
    title: "Digital. Strategy. Growth.",
    punch: "Together, let's propel your business.",
    desc: "We help you build your online presence and achieve your goals with a complete digital strategy.",
    features: ["Digital strategy", "Social media management", "Online advertising (SEA & Social Ads)", "Content & brand identity"],
    image: `${BASE}slides/slide-marketing.png`,
    gradient: "from-blue-950/95 via-blue-900/75 to-blue-800/20",
    icon: <TrendingUp className="w-7 h-7" />,
  },
];

export const T = {
  fr: {
    nav: { home: "Accueil", services: "Services", products: "Produits", contact: "Contact", cta: "Demander une démo" },
    hero_tag: "IA · Bien commun · Québec, Canada",
    hero_title_1: "Technologie au service",
    hero_title_2: "de vos idées.",
    hero_sub: "CivicAI conçoit des solutions numériques intelligentes pour les entreprises, organisations et administrations publiques — partout au Canada.",
    hero_cta: "Demander une démo",
    hero_cta2: "Voir nos services",
    trust_stats: [
      { value: "7 957", label: "services communautaires\nrépertoriés au Québec" },
      { value: "5", label: "langues supportées\nFR · EN · ES · AR · HT" },
      { value: "100 %", label: "données hébergées\nau Canada" },
      { value: "Gratuit", label: "pour les citoyens\nmodèle B2G" },
    ],
    trust_badges: [
      { icon: "🏢", label: "Entreprise québécoise", sub: "NEQ 2280791601" },
      { icon: "🔒", label: "Conforme Loi 25 QC", sub: "Protection des données" },
      { icon: "🌐", label: "Multilingue", sub: "FR · EN · ES · AR · HT" },
      { icon: "🤝", label: "Sans engagement", sub: "1re rencontre gratuite" },
    ],
    why_tag: "Pourquoi CivicAI",
    why_title: "La technologie qui travaille pour vous",
    why_sub: "Nous ne vendons pas de logiciels. Nous construisons les outils qui transforment votre façon de travailler.",
    why_items: [
      { icon: "⚡", title: "Rapide à déployer", desc: "Nos solutions sont prêtes en semaines, pas en années. Vous voyez les résultats rapidement." },
      { icon: "🎯", title: "Conçu pour vous", desc: "Chaque solution est 100 % sur mesure, adaptée à vos processus et votre réalité." },
      { icon: "🔒", title: "Sécurisé & conforme", desc: "Données hébergées au Canada, conformité Loi 25 QC, chiffrement TLS/SSL intégré." },
      { icon: "📈", title: "Résultats mesurables", desc: "KPIs définis dès le départ, tableaux de bord en temps réel, ROI transparent." },
    ],
    services_tag: "Nos services",
    services_title: "Ce que nous faisons",
    services_sub: "Des solutions technologiques complètes, de l'automatisation IA au marketing digital.",
    services_cta: "Voir tous nos services",
    products_tag: "Nos produits",
    products_title: "Solutions prêtes à déployer",
    products_sub: "Des produits CivicAI disponibles dès maintenant pour répondre à vos besoins.",
    flagship_tag: "Produit citoyen phare",
    flagship_name: "AttenteZéro",
    flagship_desc: "Un répertoire intelligent de services communautaires propulsé par l'IA. Gratuit pour tous les citoyens du Québec.",
    flagship_stats: ["7 957", "services actifs", "5", "langues", "100%", "gratuit"],
    flagship_ios: "App Store",
    flagship_android: "Google Play",
    erp_tag: "ERP · Secteur construction",
    erp_name: "ConstructPro ERP",
    erp_desc: "Un ERP moderne dédié aux entreprises de construction : gestion de projets, soumissions, équipes et finances en un seul outil.",
    erp_features: ["Gestion de projets & chantiers", "Soumissions & estimations", "Suivi d'équipes & sous-traitants", "Facturation & finances", "Rapports & tableaux de bord"],
    erp_cta: "Demander une démo",
    cta_banner_title: "Prêt à transformer votre organisation ?",
    cta_banner_sub: "Une première rencontre gratuite, sans engagement. Parlons de votre projet.",
    cta_banner_btn: "Nous contacter",
    how_tag: "Notre approche",
    how_title: "Comment ça fonctionne",
    how_sub: "Un processus simple et transparent en 3 étapes pour transformer vos idées en solutions concrètes.",
    steps: [
      { n: "01", icon: <Search className="w-6 h-6" />, title: "Analyse & découverte", desc: "Nous prenons le temps de comprendre vos besoins, vos objectifs et vos contraintes. Une rencontre gratuite sans engagement." },
      { n: "02", icon: <Palette className="w-6 h-6" />, title: "Conception & développement", desc: "Notre équipe conçoit et développe votre solution sur mesure, avec des points d'avancement réguliers." },
      { n: "03", icon: <Rocket className="w-6 h-6" />, title: "Livraison & support", desc: "Déploiement, formation et support continu. Nous restons disponibles pour faire évoluer votre solution." },
    ],
    faqs: [
      { q: "Quels sont vos délais de livraison ?", a: "Selon la complexité du projet, nos délais vont de 2 semaines (site web simple) à 6 mois (solution IA sur mesure). Nous établissons un calendrier précis lors de la rencontre initiale." },
      { q: "Comment garantissez-vous la sécurité des données ?", a: "Toutes nos solutions respectent la Loi 25 du Québec : chiffrement TLS/SSL, données hébergées au Canada, anonymisation systématique des données sensibles." },
      { q: "Travaillez-vous avec des organismes à but non lucratif ?", a: "Oui. Nous proposons des tarifs adaptés aux OBNL et organismes communautaires. AttenteZéro en est le meilleur exemple — entièrement gratuit pour les citoyens." },
      { q: "Proposez-vous du support après la livraison ?", a: "Absolument. Chaque projet inclut une période de support post-lancement, et nous proposons des contrats de maintenance et d'évolution." },
      { q: "Comment se déroule la première rencontre ?", a: "La première rencontre est gratuite et sans engagement. Nous découvrons vos besoins et vous repartirez avec une proposition préliminaire sous 48h." },
    ],
    contact_tag: "Contact",
    contact_title: "Parlons de votre projet",
    contact_sub: "Entreprise, organisme ou administration publique ? Décrivez-nous votre projet.",
    form_name: "Nom complet",
    form_org: "Organisation",
    form_email: "Adresse courriel",
    form_phone: "Téléphone (optionnel)",
    form_service: "Service souhaité",
    form_service_options: ["IA & Automatisation", "Solutions sur mesure", "Optimisation IA", "Développement web", "Marketing digital", "ConstructPro ERP", "Autre"],
    form_msg: "Décrivez votre projet...",
    form_send: "Envoyer la demande",
    form_success: "Merci ! Nous vous répondrons sous 48h.",
    footer_tagline: "TECHNOLOGIE AU SERVICE DE VOS IDÉES",
    footer_copy: "© 2026 CivicAI — NEQ 2280791601 — Québec, Canada",
    footer_links_services: "Services",
    footer_links_products: "Produits",
    footer_links_legal: "Légal",
    footer_privacy: "Politique de confidentialité",
    footer_about: "À propos",
    slides: SLIDES_FR,
  },
  en: {
    nav: { home: "Home", services: "Services", products: "Products", contact: "Contact", cta: "Request a demo" },
    hero_tag: "AI · Public Good · Quebec, Canada",
    hero_title_1: "Technology at the service",
    hero_title_2: "of your ideas.",
    hero_sub: "CivicAI designs intelligent digital solutions for businesses, organizations, and public administrations — across Canada.",
    hero_cta: "Request a demo",
    hero_cta2: "See our services",
    trust_stats: [
      { value: "7,957", label: "community services\nlisted in Quebec" },
      { value: "5", label: "supported languages\nFR · EN · ES · AR · HT" },
      { value: "100%", label: "data hosted\nin Canada" },
      { value: "Free", label: "for citizens\nB2G model" },
    ],
    trust_badges: [
      { icon: "🏢", label: "Quebec company", sub: "QEI 2280791601" },
      { icon: "🔒", label: "Law 25 QC compliant", sub: "Data protection" },
      { icon: "🌐", label: "Multilingual", sub: "FR · EN · ES · AR · HT" },
      { icon: "🤝", label: "No commitment", sub: "Free first meeting" },
    ],
    why_tag: "Why CivicAI",
    why_title: "Technology that works for you",
    why_sub: "We don't sell software. We build the tools that transform how you work.",
    why_items: [
      { icon: "⚡", title: "Fast to deploy", desc: "Our solutions are ready in weeks, not years. You see results quickly." },
      { icon: "🎯", title: "Built for you", desc: "Every solution is 100% custom, adapted to your processes and reality." },
      { icon: "🔒", title: "Secure & compliant", desc: "Data hosted in Canada, Law 25 QC compliance, built-in TLS/SSL encryption." },
      { icon: "📈", title: "Measurable results", desc: "KPIs defined from day one, real-time dashboards, transparent ROI." },
    ],
    services_tag: "Our services",
    services_title: "What we do",
    services_sub: "Complete technology solutions, from AI automation to digital marketing.",
    services_cta: "See all services",
    products_tag: "Our products",
    products_title: "Ready-to-deploy solutions",
    products_sub: "CivicAI products available now to meet your needs.",
    flagship_tag: "Flagship civic product",
    flagship_name: "AttenteZéro",
    flagship_desc: "An AI-powered directory of community services — free for all citizens of Quebec.",
    flagship_stats: ["7,957", "active services", "5", "languages", "100%", "free"],
    flagship_ios: "App Store",
    flagship_android: "Google Play",
    erp_tag: "ERP · Construction sector",
    erp_name: "ConstructPro ERP",
    erp_desc: "A modern ERP dedicated to construction companies: project management, bids, teams, and finances in one tool.",
    erp_features: ["Project & site management", "Bids & estimates", "Team & subcontractor tracking", "Invoicing & finances", "Reports & dashboards"],
    erp_cta: "Request a demo",
    cta_banner_title: "Ready to transform your organization?",
    cta_banner_sub: "A free first meeting, no commitment. Let's talk about your project.",
    cta_banner_btn: "Contact us",
    how_tag: "Our approach",
    how_title: "How it works",
    how_sub: "A simple, transparent 3-step process to turn your ideas into concrete solutions.",
    steps: [
      { n: "01", icon: <Search className="w-6 h-6" />, title: "Analysis & discovery", desc: "We take time to understand your needs, goals, and constraints. A free initial meeting, no commitment required." },
      { n: "02", icon: <Palette className="w-6 h-6" />, title: "Design & development", desc: "Our team designs and builds your custom solution with regular progress updates and your feedback integrated." },
      { n: "03", icon: <Rocket className="w-6 h-6" />, title: "Delivery & support", desc: "Deployment, training, and ongoing support. We stay available to evolve your solution with you." },
    ],
    faqs: [
      { q: "What are your delivery timelines?", a: "Depending on complexity, our timelines range from 2 weeks (simple website) to 6 months (custom AI solution). We set a precise schedule at the initial meeting." },
      { q: "How do you guarantee data security?", a: "All our solutions comply with Quebec's Law 25: TLS/SSL encryption, data hosted in Canada, systematic anonymization of sensitive data." },
      { q: "Do you work with non-profit organizations?", a: "Yes. We offer adapted pricing for non-profits and community organizations. AttenteZéro is the best example — entirely free for citizens." },
      { q: "Do you offer post-delivery support?", a: "Absolutely. Every project includes a post-launch support period, and we offer maintenance and evolution contracts." },
      { q: "How does the first meeting work?", a: "The first meeting is free and without commitment. We discover your needs and you'll receive a preliminary proposal within 48 hours." },
    ],
    contact_tag: "Contact",
    contact_title: "Let's talk about your project",
    contact_sub: "Business, organization, or public administration? Tell us about your project.",
    form_name: "Full name",
    form_org: "Organization",
    form_email: "Email address",
    form_phone: "Phone (optional)",
    form_service: "Desired service",
    form_service_options: ["AI & Automation", "Custom solutions", "AI Optimization", "Web development", "Digital marketing", "ConstructPro ERP", "Other"],
    form_msg: "Describe your project...",
    form_send: "Send request",
    form_success: "Thank you! We'll get back to you within 48h.",
    footer_tagline: "TECHNOLOGY AT THE SERVICE OF YOUR IDEAS",
    footer_copy: "© 2026 CivicAI — QEI 2280791601 — Quebec, Canada",
    footer_links_services: "Services",
    footer_links_products: "Products",
    footer_links_legal: "Legal",
    footer_privacy: "Privacy policy",
    footer_about: "About",
    slides: SLIDES_EN,
  },
} as const;

export type TType = typeof T.fr;

interface LangContextType {
  lang: Lang;
  setLang: (l: Lang) => void;
}

const LangContext = createContext<LangContextType>({ lang: "fr", setLang: () => {} });

export function LangProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Lang>("fr");
  return <LangContext.Provider value={{ lang, setLang }}>{children}</LangContext.Provider>;
}

export function useLang() {
  return useContext(LangContext);
}
