import type { Category } from "@/data/services";

interface DetectionResult {
  category: Category | null;
  confidence: "high" | "medium" | "low";
  keywords: string[];
}

const KEYWORD_MAP: Record<Category, string[]> = {
  housing: [
    "logement",
    "loger",
    "dormir",
    "nuit",
    "refuge",
    "abri",
    "hébergement",
    "maison",
    "appartement",
    "sans toit",
    "itinérant",
    "itinérance",
    "expulsé",
    "expulsion",
    "rue",
    "sans abri",
    "sdf",
    "loyer",
    "housing",
    "sleep",
    "homeless",
    "shelter",
    "nowhere to sleep",
    "evict",
    "nowhere to go",
    "nulle part",
    "bivouac",
    "camping",
    "tente",
    "dehors",
    "outside",
  ],
  food: [
    "faim",
    "manger",
    "nourriture",
    "aliment",
    "épicerie",
    "repas",
    "bouffe",
    "affamé",
    "food",
    "hungry",
    "eat",
    "groceries",
    "pantry",
    "banque alimentaire",
    "garde-manger",
    "pain",
    "dîner",
    "souper",
    "déjeuner",
    "cuisine",
    "provisions",
    "je n'ai rien à manger",
    "nothing to eat",
    "no food",
    "pas de nourriture",
  ],
  mentalHealth: [
    "stress",
    "anxiété",
    "dépression",
    "suicide",
    "suicidaire",
    "détresse",
    "mental",
    "psychologique",
    "psy",
    "anxieux",
    "triste",
    "désespoir",
    "désespéré",
    "crise",
    "crisis",
    "anxiety",
    "depressed",
    "depression",
    "stressed",
    "overwhelmed",
    "dépassé",
    "burn out",
    "burnout",
    "épuisement",
    "panique",
    "panic",
    "seul",
    "solitude",
    "alone",
    "lonely",
    "isolation",
    "pensées sombres",
    "dark thoughts",
    "mourir",
    "je veux mourir",
    "want to die",
    "plus envie de vivre",
    "dormir",
    "sleep",
    "troubles du sommeil",
    "peur",
    "fear",
    "je n'en peux plus",
    "can't take it anymore",
    "traumatisme",
    "trauma",
    "violence",
  ],
  health: [
    "santé",
    "médecin",
    "docteur",
    "malade",
    "maladie",
    "médicament",
    "soins",
    "hôpital",
    "clinique",
    "urgence médicale",
    "sick",
    "health",
    "doctor",
    "medicine",
    "hospital",
    "pain",
    "douleur",
    "blessé",
    "injured",
    "infection",
    "fièvre",
    "fever",
    "blessure",
    "accident",
    "assurance maladie",
    "ramq",
    "carte soleil",
    "sans carte",
    "no coverage",
    "prescription",
    "ordonnance",
    "dentiste",
    "dental",
  ],
  immigration: [
    "immigration",
    "immigrant",
    "réfugié",
    "asylum",
    "asile",
    "visa",
    "permis de séjour",
    "statut",
    "sans papiers",
    "undocumented",
    "déportation",
    "deportation",
    "demande d'asile",
    "refugee",
    "migrant",
    "francisation",
    "français",
    "langue",
    "intégration",
    "nouveau arrivant",
    "newcomer",
    "citizenship",
    "citoyenneté",
    "résidence permanente",
    "permanent resident",
    "travail permit",
    "permis de travail",
  ],
  employment: [
    "emploi",
    "travail",
    "job",
    "chômage",
    "chômeur",
    "sans emploi",
    "trouver un emploi",
    "chercher du travail",
    "cv",
    "curriculum",
    "entretien",
    "interview",
    "formation professionnelle",
    "apprentissage",
    "unemployed",
    "work",
    "career",
    "aide sociale",
    "bs",
    "prestation",
    "assurance emploi",
    "ae",
    "job loss",
    "perte d'emploi",
    "licencié",
    "congédié",
    "fired",
    "revenu",
    "income",
    "money",
    "argent",
    "finances",
    "financier",
  ],
  family: [
    "famille",
    "enfant",
    "enfants",
    "parent",
    "violence conjugale",
    "conjoint",
    "époux",
    "mari",
    "femme",
    "femmes battues",
    "abus",
    "maltraitance",
    "domestic violence",
    "family",
    "children",
    "child",
    "abuse",
    "beaten",
    "battered",
    "custody",
    "garde",
    "divorce",
    "séparation",
    "monoparentale",
    "single parent",
    "bébé",
    "baby",
    "grossesse",
    "pregnant",
    "jeune",
    "ado",
    "teenager",
    "adolescent",
    "dpj",
    "protection jeunesse",
    "protection enfance",
  ],
  social: [
    "soutien",
    "aide",
    "help",
    "support",
    "communauté",
    "community",
    "bénévolat",
    "volunteer",
    "accompagnement",
    "orientation",
    "ressources",
    "resources",
    "aîné",
    "âgé",
    "elderly",
    "senior",
    "handicap",
    "disability",
    "handicapé",
    "isolé",
    "isolated",
    "seul",
    "alone",
    "lien social",
    "groupe de soutien",
    "support group",
    "je ne sais pas",
    "don't know",
    "où aller",
    "where to go",
    "general",
  ],
};

export function detectCategory(input: string): DetectionResult {
  const normalized = input.toLowerCase().trim();
  const scores: Record<Category, number> = {
    housing: 0,
    food: 0,
    mentalHealth: 0,
    health: 0,
    immigration: 0,
    employment: 0,
    family: 0,
    social: 0,
  };
  const matchedKeywords: string[] = [];

  for (const [cat, keywords] of Object.entries(KEYWORD_MAP) as [
    Category,
    string[],
  ][]) {
    for (const kw of keywords) {
      if (normalized.includes(kw)) {
        scores[cat] += kw.split(" ").length;
        if (!matchedKeywords.includes(kw)) matchedKeywords.push(kw);
      }
    }
  }

  const maxScore = Math.max(...Object.values(scores));

  if (maxScore === 0) {
    return { category: null, confidence: "low", keywords: [] };
  }

  const topCategory = (
    Object.entries(scores) as [Category, number][]
  ).reduce((a, b) => (b[1] > a[1] ? b : a))[0];

  const confidence =
    maxScore >= 3 ? "high" : maxScore >= 1 ? "medium" : "low";

  return {
    category: topCategory,
    confidence,
    keywords: matchedKeywords,
  };
}
