import type { Category } from "@/data/services";

interface DetectionResult {
  category: Category | null;
  confidence: "high" | "medium" | "low";
  keywords: string[];
}

const KEYWORD_MAP: Record<Category, string[]> = {
  administrative: [],
  legal: [],
  hypermarche: [
    "walmart", "supercentre", "supercenter",
    "hypermarché", "hypermarche", "hypermarchés",
    "costco", "maxi", "super c", "super-c",
    "loblaws", "métro", "iga",
  ],
  banking: [
    "banque", "banques", "banking", "bank",
    "compte bancaire", "ouvrir un compte", "open account",
    "carte de crédit", "credit card", "carte de débit",
    "prêt", "loan", "hypothèque", "mortgage",
    "desjardins", "rbc", "scotia", "scotiabank", "bmo",
    "cibc", "td", "td canada trust", "banque nationale",
    "atb", "vancity", "credit union", "coopérative",
    "guichet", "atm", "interac", "transfert",
  ],
  transport: [
    "transport", "transporter", "transportation",
    "uber", "uber eats", "lyft",
    "taxi", "ride", "course",
    "livraison", "delivery", "courrier",
    "freight", "marchandise",
  ],
  moving: [
    "déménagement", "déménager", "déménageur", "déménageurs",
    "move", "moving", "movers", "mover",
    "boîtes", "cartons", "boxes",
    "camion déménagement", "moving truck",
    "1er juillet", "july 1st", "fête du déménagement",
    "clan panneton", "déménagement dg", "la capitale déménagement",
    "armstrong déménagement", "crown movers",
    "ctq", "transporteur",
    "entreposage", "storage",
  ],
  tourism: [
    "tourisme", "tourist", "touriste", "visiter", "visit",
    "attraction", "attractions", "incontournable",
    "vieux-québec", "vieux-montréal", "château frontenac",
    "mont-royal", "tadoussac", "gaspésie", "saguenay",
    "fjord", "rocher percé", "valcartier",
    "musée", "museum", "jardin botanique",
    "voyage", "vacances", "excursion", "sortie",
    "balade", "promenade", "patrimoine",
  ],
  housing: [
    "logement",
    "loger",
    "dormir",
    "nuit",
    "refuge",
    "abri",
    "hébergement",
    "maison",
    "appartement",
    "sans toit",
    "itinérant",
    "itinérance",
    "expulsé",
    "expulsion",
    "rue",
    "sans abri",
    "sdf",
    "loyer",
    "housing",
    "sleep",
    "homeless",
    "shelter",
    "nowhere to sleep",
    "evict",
    "nowhere to go",
    "nulle part",
    "bivouac",
    "camping",
    "tente",
    "dehors",
    "outside",
  ],
  food: [
    "faim",
    "manger",
    "nourriture",
    "aliment",
    "épicerie",
    "repas",
    "bouffe",
    "affamé",
    "food",
    "hungry",
    "eat",
    "groceries",
    "pantry",
    "banque alimentaire",
    "garde-manger",
    "pain",
    "dîner",
    "souper",
    "déjeuner",
    "cuisine",
    "provisions",
    "je n'ai rien à manger",
    "nothing to eat",
    "no food",
    "pas de nourriture",
  ],
  mentalHealth: [
    "stress",
    "anxiété",
    "dépression",
    "suicide",
    "suicidaire",
    "détresse",
    "mental",
    "psychologique",
    "psy",
    "anxieux",
    "triste",
    "désespoir",
    "désespéré",
    "crise",
    "crisis",
    "anxiety",
    "depressed",
    "depression",
    "stressed",
    "overwhelmed",
    "dépassé",
    "burn out",
    "burnout",
    "épuisement",
    "panique",
    "panic",
    "seul",
    "solitude",
    "alone",
    "lonely",
    "isolation",
    "pensées sombres",
    "dark thoughts",
    "mourir",
    "je veux mourir",
    "want to die",
    "plus envie de vivre",
    "dormir",
    "sleep",
    "troubles du sommeil",
    "peur",
    "fear",
    "je n'en peux plus",
    "can't take it anymore",
    "traumatisme",
    "trauma",
    "violence",
    "drogue",
    "drogues",
    "cocaïne",
    "héroïne",
    "crack",
    "fentanyl",
    "opioïde",
    "overdose",
    "dépendance",
    "addiction",
    "alcool",
    "alcoolisme",
    "boire",
    "ivre",
    "drunk",
    "alcohol",
    "drug",
    "substance",
    "jeu compulsif",
    "jeu pathologique",
    "gambling",
    "casino",
    "je joue trop",
    "tel-jeunes",
    "jeunesse",
    "jeune en crise",
    "ado en crise",
    "adolescent suicidaire",
    "enfant en danger",
    "narcotiques",
    "alcooliques anonymes",
    "na québec",
    "aa québec",
  ],
  health: [
    "santé",
    "médecin",
    "docteur",
    "malade",
    "maladie",
    "médicament",
    "soins",
    "hôpital",
    "clinique",
    "urgence médicale",
    "sick",
    "health",
    "doctor",
    "medicine",
    "hospital",
    "pain",
    "douleur",
    "blessé",
    "injured",
    "infection",
    "fièvre",
    "fever",
    "blessure",
    "accident",
    "assurance maladie",
    "ramq",
    "carte soleil",
    "sans carte",
    "no coverage",
    "prescription",
    "ordonnance",
    "dentiste",
    "dental",
  ],
  immigration: [
    "immigration",
    "immigrant",
    "réfugié",
    "asylum",
    "asile",
    "visa",
    "permis de séjour",
    "statut",
    "sans papiers",
    "undocumented",
    "déportation",
    "deportation",
    "demande d'asile",
    "refugee",
    "migrant",
    "francisation",
    "français",
    "langue",
    "intégration",
    "nouveau arrivant",
    "newcomer",
    "citizenship",
    "citoyenneté",
    "résidence permanente",
    "permanent resident",
    "travail permit",
    "permis de travail",
  ],
  employment: [
    "emploi",
    "travail",
    "job",
    "chômage",
    "chômeur",
    "sans emploi",
    "trouver un emploi",
    "chercher du travail",
    "cv",
    "curriculum",
    "entretien",
    "interview",
    "formation professionnelle",
    "apprentissage",
    "unemployed",
    "work",
    "career",
    "aide sociale",
    "bs",
    "prestation",
    "assurance emploi",
    "ae",
    "job loss",
    "perte d'emploi",
    "licencié",
    "congédié",
    "fired",
    "revenu",
    "income",
    "money",
    "argent",
    "finances",
    "financier",
  ],
  family: [
    "famille",
    "enfant",
    "enfants",
    "parent",
    "violence conjugale",
    "conjoint",
    "époux",
    "mari",
    "femme",
    "femmes battues",
    "abus",
    "maltraitance",
    "domestic violence",
    "family",
    "children",
    "child",
    "abuse",
    "beaten",
    "battered",
    "custody",
    "garde",
    "divorce",
    "séparation",
    "monoparentale",
    "single parent",
    "bébé",
    "baby",
    "grossesse",
    "pregnant",
    "jeune",
    "ado",
    "teenager",
    "adolescent",
    "dpj",
    "protection jeunesse",
    "protection enfance",
    "abus aîné",
    "maltraitance aîné",
    "violence aîné",
    "elder abuse",
    "agression sexuelle",
    "viol",
    "sexual assault",
    "rape",
    "calacs",
    "inceste",
    "harcèlement sexuel",
    "traite",
    "trafic humain",
    "exploitation sexuelle",
    "grossesse",
    "pregnant",
    "enceinte",
    "grossesse non désirée",
    "avortement",
    "sos grossesse",
    "sinistre",
    "incendie",
    "inondation",
    "feu maison",
    "disaster",
    "urgence civile",
    "croix rouge",
    "sécurité civile",
  ],
  social: [
    "soutien",
    "aide",
    "help",
    "support",
    "communauté",
    "community",
    "bénévolat",
    "volunteer",
    "accompagnement",
    "orientation",
    "ressources",
    "resources",
    "aîné",
    "âgé",
    "elderly",
    "senior",
    "handicap",
    "disability",
    "handicapé",
    "isolé",
    "isolated",
    "seul",
    "alone",
    "lien social",
    "groupe de soutien",
    "support group",
    "je ne sais pas",
    "don't know",
    "où aller",
    "where to go",
    "general",
    "concessionnaire",
    "achat de voiture",
    "acheter une voiture",
    "acheter voiture",
    "voiture",
    "automobile",
    "véhicule",
    "auto",
    "voiture d'occasion",
    "véhicule d'occasion",
    "financement auto",
    "financement voiture",
    "assurance auto",
    "assurance automobile",
    "assurance voiture",
    "beneva",
    "promutuel",
    "intact assurance",
    "belairdirect",
    "desjardins assurance",
    "car dealership",
    "buy car",
    "car insurance",
    "used car",
    "dealer",
    "honda",
    "toyota",
    "ford",
    "hyundai",
    "kia",
    "subaru",
    "volkswagen",
    "nissan",
    "mazda",
    "police",
    "policier",
    "sûreté",
    "gendarmerie",
    "grc",
    "spvm",
    "911",
    "signaler un crime",
    "criminel",
    "crime",
    "voleur",
    "vol",
    "sécurité publique",
    "pompier",
    "feu",
    "flammes",
    "brûlé",
    "incendie maison",
    "fumée",
    "firefighter",
    "ambulance",
    "paramédic",
    "paramedic",
    "secours",
    "urgences santé",
    "premiers soins",
    "soins d'urgence",
    "centre 911",
    "center 911",
    "dispatch",
    "premiers répondants",
    "first responders",
    "pompiers volontaires",
    "caserne",
    "fire station",
    "incendie forêt",
    "feu de forêt",
    "wildfire",
    "sauvetage",
    "rescue",
    "matières dangereuses",
    "hazmat",
  ],
  realestate: [
    "achat maison",
    "acheter maison",
    "acheter une maison",
    "achat immobilier",
    "immobilier",
    "propriété",
    "maison à vendre",
    "condo à vendre",
    "acheter condo",
    "prêt hypothécaire",
    "hypothèque",
    "hypothécaire",
    "mise de fonds",
    "courtier immobilier",
    "agent immobilier",
    "centris",
    "duproprio",
    "mls",
    "schl",
    "cmhc",
    "rap",
    "régime accession",
    "celiapp",
    "premier acheteur",
    "première propriété",
    "first home",
    "home buying",
    "mortgage",
    "down payment",
    "real estate",
    "buy house",
    "buy condo",
    "financement maison",
    "prêt maison",
    "notaire achat",
    "inspection maison",
    "offre d'achat",
    "prix maison",
    "marché immobilier",
    "investissement immobilier",
    "desjardins hypothèque",
    "banque nationale hypothèque",
    "rbc hypothèque",
    "td hypothèque",
    "bmo hypothèque",
    "logement propriétaire",
    "devenir propriétaire",
    "accession propriété",
  ],
  childcare: [
    "garderie",
    "cpe",
    "centre de la petite enfance",
    "service de garde",
    "services de garde",
    "garde enfant",
    "garde d'enfant",
    "garde d'enfants",
    "halte-garderie",
    "halte garderie",
    "milieu familial",
    "rsg",
    "responsable service de garde",
    "liste d'attente garderie",
    "liste attente cpe",
    "mon enfant",
    "monenfant",
    "subventionné garderie",
    "garderie subventionnée",
    "garderie non subventionnée",
    "place en garderie",
    "place garderie",
    "trouver garderie",
    "inscription garderie",
    "inscription cpe",
    "frais de garde",
    "10 par jour",
    "10$/jour",
    "daycare",
    "childcare",
    "child care",
    "nursery",
    "preschool",
    "pre-school",
    "subsidized daycare",
    "babysitter",
    "babysitting",
    "garde à domicile",
    "nourrisson",
    "bébé garde",
    "pouponnière",
    "poupon",
    "maternelle",
    "garderie pas chère",
    "garde abordable",
    "affordable childcare",
  ],
};

export function detectCategory(input: string): DetectionResult {
  const normalized = input.toLowerCase().trim();
  const scores: Record<Category, number> = {
    housing: 0,
    food: 0,
    mentalHealth: 0,
    health: 0,
    immigration: 0,
    employment: 0,
    family: 0,
    social: 0,
    childcare: 0,
    realestate: 0,
    administrative: 0,
    legal: 0,
    banking: 0,
    transport: 0,
    tourism: 0,
    moving: 0,
    hypermarche: 0,
  };
  const matchedKeywords: string[] = [];

  for (const [cat, keywords] of Object.entries(KEYWORD_MAP) as [
    Category,
    string[],
  ][]) {
    for (const kw of keywords) {
      if (normalized.includes(kw)) {
        scores[cat] += kw.split(" ").length;
        if (!matchedKeywords.includes(kw)) matchedKeywords.push(kw);
      }
    }
  }

  const maxScore = Math.max(...Object.values(scores));

  if (maxScore === 0) {
    return { category: null, confidence: "low", keywords: [] };
  }

  const topCategory = (
    Object.entries(scores) as [Category, number][]
  ).reduce((a, b) => (b[1] > a[1] ? b : a))[0];

  const confidence =
    maxScore >= 3 ? "high" : maxScore >= 1 ? "medium" : "low";

  return {
    category: topCategory,
    confidence,
    keywords: matchedKeywords,
  };
}
